from app.services.email.email_service import (
    EmailService,
    COURSE_COMPLETION_TEMPLATE,
    ENROLLMENT_NOTIFICATION_TEMPLATE,
    PROGRESS_REPORT_TEMPLATE,
    SUBMISSION_NOTIFICATION_TEMPLATE,
)

__all__ = [
    "EmailService",
    "ENROLLMENT_NOTIFICATION_TEMPLATE",
    "SUBMISSION_NOTIFICATION_TEMPLATE",
    "COURSE_COMPLETION_TEMPLATE",
    "PROGRESS_REPORT_TEMPLATE",
]
