"""test

Revision ID: f63d286470cd
Revises: cba921310bd9
Create Date: 2025-12-16 20:04:57.332623

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f63d286470cd"
down_revision = 'cba921310bd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

